import {useEffect,useMemo,useRef,useState} from 'react';
import {ChoiceControl,StepControl,SearchChoice,StudyWorkbench,StudyControlPanel} from './StudyControls';
import {focusStudyResult} from '../lib/useEvaluatedScenario';
import {mobilityAll,mobilityLabels,mobilityPolicies,type MobilityStation,type MobilityDay,type MobilityPolicy} from '../lib/mobility';
type Summary={budget:number;touch_limit:number;policy:string;mean_residual:number;[key:string]:unknown};
type Index={meta:{default_date:string;default_budget?:number;default_touch_limit?:number;budget_grid:number[];touch_grid:number[];selected_history:number;[key:string]:unknown};stations:MobilityStation[];days:MobilityDay[];summaries:Summary[];[key:string]:unknown};
const fmt=(v:number,digits=0)=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:digits}).format(v);
const signed=(v:number)=>`${v>0?'+':''}${fmt(v,1)}`;
const labelDate=(v:string)=>new Date(v+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'});
export default function MobilityExplorer({index}:{index:Index}){
 const [ready,setReady]=useState(false),inspector=useRef<HTMLDivElement>(null),resultRegion=useRef<HTMLDivElement>(null),[periodBaseline,setPeriodBaseline]=useState<'no_action'|'greedy'>('no_action'),[focusTarget,setFocusTarget]=useState<'result'|'station'|null>(null);
 useEffect(()=>setReady(true),[]);
 const [date,setDate]=useState(index.meta.default_date),[budget,setBudget]=useState(index.meta.default_budget??200),[touch,setTouch]=useState(index.meta.default_touch_limit??20),[protectedId,setProtected]=useState(''),[inspectId,setInspect]=useState(index.stations[0].id),[showAll,setShowAll]=useState(false);
 useEffect(()=>{if(!focusTarget)return;const target=focusTarget==='result'?resultRegion.current:inspector.current;focusStudyResult(target);setFocusTarget(null);},[focusTarget,date,inspectId,protectedId]);
 const day=index.days.find(d=>d.date===date)!,protectedIndex=protectedId?index.stations.findIndex(s=>s.id===protectedId):null;
 const policies=useMemo(()=>mobilityAll(index.stations,day,budget,touch,protectedIndex),[index,day,budget,touch,protectedIndex]);
 const plan=policies.optimized,delta=plan.residual-policies.no_action.residual,inspect=index.stations.findIndex(s=>s.id===inspectId);
 const curve=useMemo(()=>index.meta.budget_grid.map(B=>({budget:B,...mobilityAll(index.stations,day,B,touch,protectedIndex).optimized})),[index,day,touch,protectedIndex]);
 const period=useMemo(()=>index.days.map(d=>{const p=mobilityAll(index.stations,d,budget,touch);return {date:d.date,delta:p.optimized.residual-p[periodBaseline].residual,residual:p.optimized.residual};}),[index,budget,touch,periodBaseline]);
 const worst=[...period].sort((a,b)=>b.delta-a.delta||a.date.localeCompare(b.date))[0];
 const transfers=index.stations.map((s,i)=>({...s,i,r:plan.transfer[i]})).filter(s=>s.r!==0);
 const removed=transfers.filter(s=>s.r<0).sort((a,b)=>a.r-b.r||a.id.localeCompare(b.id)),added=transfers.filter(s=>s.r>0).sort((a,b)=>b.r-a.r||a.id.localeCompare(b.id));
 const network=index.stations.map((s,i)=>({...s,i})).sort((a,b)=>Math.abs(day.actual[b.i]-plan.transfer[b.i])-Math.abs(day.actual[a.i]-plan.transfer[a.i])||a.id.localeCompare(b.id));
 const maxBar=Math.max(1,...transfers.map(s=>Math.abs(s.r))),maxCurve=Math.max(1,...curve.map(r=>r.residual));
 const stationOptions=index.stations.map(s=>({value:s.id,label:`${s.name} · ${s.id}${s.eligible?'':' · outside cohort'}`}));
 const resetScenario=()=>{setDate(index.meta.default_date);setBudget(index.meta.default_budget??200);setTouch(index.meta.default_touch_limit??20);setProtected('');};
 function inspectMorning(value:string){setProtected('');setDate(value);setFocusTarget('result');}
 function showAdverse(){inspectMorning(worst.date);}
 return <fieldset className="mobility-tool" disabled={!ready}><legend className="sr-only">Interactive cycle-hire allocation</legend>
  <StudyWorkbench>
  <StudyControlPanel summary={`${labelDate(date)} · ${budget}-bike / ${touch}-station limits${protectedId?' · station protected':''} · ${fmt(plan.residual)} residual flow units · ${plan.moves} moved`}>
   <StepControl label="Morning to evaluate" value={date} options={index.days.map(d=>({value:d.date,label:labelDate(d.date)}))} onChange={setDate} disabled={!ready}/>
   <StepControl label="Bikes available to move" value={budget} options={index.meta.budget_grid.map(B=>({value:B,label:`${B} bikes maximum`}))} onChange={setBudget} disabled={!ready}/>
   <StepControl label="Stations allowed to change" value={touch} options={index.meta.touch_grid.map(K=>({value:K,label:`${K} stations maximum`}))} onChange={setTouch} disabled={!ready}/>
   <div className="study-preset-row" role="group" aria-label="Rebalancing presets"><button onClick={resetScenario}>Reference scenario</button><button onClick={()=>{setBudget(index.meta.budget_grid[0]);setProtected('');}}>Smallest move budget</button><button onClick={()=>{setBudget(index.meta.budget_grid[index.meta.budget_grid.length-1]);setTouch(index.meta.touch_grid[index.meta.touch_grid.length-1]);setProtected('');}}>Largest tested limits</button></div>
   <p className="mobility-small">{protectedId?`Protected: ${index.stations.find(s=>s.id===protectedId)!.name}.`:'No station protected.'} Protect an individual station in the station inspector below. The complete-period comparison always remains unprotected.</p>
   {protectedId&&<button className="mobility-text-button" onClick={()=>setProtected('')}>Clear station protection</button>}
  </StudyControlPanel>
  <div className="study-workbench-results">
  <div className="mobility-live" ref={resultRegion} tabIndex={-1} id="mobility-selected-result" aria-live="polite" aria-atomic="true"><p><strong>{labelDate(date)}</strong> · {plan.moves} bikes moved · {plan.touched} stations changed · {delta===0?'same residual as no relocation':`${fmt(Math.abs(delta))} ${delta<0?'fewer':'more'} residual flow units than no relocation`}.</p></div>
  <div className="mobility-kpis"><div><span>Residual observed flow</span><strong>{fmt(plan.residual)}</strong><small>Lower is closer to balance</small></div><div><span>Bikes moved</span><strong>{plan.moves}<small> / {budget}</small></strong><small>{plan.unused_budget} budget units unused</small></div><div><span>Stations changed</span><strong>{plan.touched}<small> / {touch}</small></strong><small>Of {index.stations.filter(s=>s.eligible).length} eligible stations</small></div></div>
  <p className="mobility-decision-note">{plan.moves===0?'These settings produce no beneficial conserved transfer. At least two stations, opposing forecast flows and a positive paired improvement are needed.':`The plan takes ${plan.moves} bikes from ${removed.length} stations and adds the same number to ${added.length} other ${added.length===1?'station':'stations'}. ${plan.moves===budget?'The bike budget is fully used.':'No further beneficial transfer fits these limits.'} ${plan.touched===touch?'The station-touch cap is fully used.':''}`} {delta>0?'On the recorded morning, this plan makes the flow-balance score worse.':''} {policies.greedy.forecast_residual_num===plan.forecast_residual_num?'The greedy rule ties the exact forecast objective here.':''}</p>
  <div className="mobility-transfer-panel"><div className="mobility-panel-heading"><h3>Where the effort goes</h3><p>Exact allocation · net transfers, not truck routes</p></div>
   <div className="mobility-transfer-grid">{[{title:'Take from',rows:removed,sign:'−',kind:'remove'},{title:'Add to',rows:added,sign:'+',kind:'add'}].map(group=><div key={group.title} className={`mobility-transfer-side ${group.kind}`}><h4>{group.title}<span>{plan.moves} bikes</span></h4>{group.rows.length?<ol>{group.rows.map(s=><li key={s.id}><button onClick={()=>{setInspect(s.id);setFocusTarget('station');}} aria-label={`Inspect ${s.name}`}><span>{s.name}</span><strong>{group.sign}{Math.abs(s.r)}</strong></button><div className="mobility-transfer-track"><span style={{width:`${Math.abs(s.r)/maxBar*100}%`}} /></div></li>)}</ol>:<p>No transfers at these settings.</p>}</div>)}</div>
   <p className="mobility-conservation">{plan.moves} removed = {plan.moves} added <span> · net new bikes: 0</span></p>
  </div>
  <section className="mobility-panel" aria-labelledby="mobility-policy-heading"><h3 id="mobility-policy-heading">Did the plan hold up?</h3><p>Each plan is scored against the same observed morning. The perfect-information row knows that morning in advance; the other plans do not.</p><div className="table-wrap" tabIndex={0} role="region" aria-label="Policy comparison"><table><caption>{labelDate(date)} · {budget} bikes · {touch} stations · {protectedId?'one protected station':'no protection'}</caption><thead><tr><th>Policy</th><th>Forecast residual</th><th>Observed residual</th><th>Bikes moved</th><th>Stations</th></tr></thead><tbody>{mobilityPolicies.map(p=><tr key={p} className={p==='optimized'?'selected-policy':''}><th scope="row">{mobilityLabels[p]}</th><td>{p==='oracle'?'Not a forecast plan':fmt(policies[p].forecast_residual,1)}</td><td>{fmt(policies[p].residual)}</td><td>{policies[p].moves}</td><td>{policies[p].touched}</td></tr>)}</tbody></table></div><p>The full network records {fmt(day.departures.reduce((a,b)=>a+b,0))} departures and {fmt(day.arrivals.reduce((a,b)=>a+b,0))} arrivals. Its net outflow is {signed(day.actual.reduce((a,b)=>a+b,0))}; conservation alone sets a lower bound of {fmt(plan.net_flow_bound)} on total residual. Forecast scores cover the admitted cohort; observed scores include all {index.stations.length} ordinary stations.</p></section>
  <div className="mobility-panel mobility-inspect" ref={inspector} tabIndex={-1} id="mobility-station"><h3>Look inside a station</h3><SearchChoice label="Find a station" value={inspectId} options={stationOptions} onChange={setInspect} disabled={!ready} help="Search by station name or ID, or select a transfer above."/><div className="study-preset-row"><button disabled={!index.stations[inspect].eligible||protectedId===inspectId} onClick={()=>setProtected(inspectId)}>{protectedId===inspectId?'This station is protected':'Protect this station from transfers'}</button>{protectedId&&<button onClick={()=>setProtected('')}>Clear station protection</button>}</div><p className="mobility-small">Protection is a hypothetical restriction, not an observed closure. It applies to all four plans for the selected morning. Stations outside the cohort already receive no intervention.</p><div className="mobility-station-stats"><div><span>Departures / arrivals</span><strong>{day.departures[inspect]} / {day.arrivals[inspect]}</strong></div><div><span>Forecast net outflow</span><strong>{day.forecast_num[inspect]===null?'N/A':signed(day.forecast_num[inspect]!/60)}</strong></div><div><span>Observed net outflow</span><strong>{signed(day.actual[inspect])}</strong></div><div><span>Net transfer</span><strong>{signed(plan.transfer[inspect])}</strong></div><div><span>Remaining net outflow</span><strong>{signed(day.actual[inspect]-plan.transfer[inspect])}</strong></div></div><p>{index.stations[inspect].eligible?`Forecast uses ${day.history_count[inspect]} available earlier same-weekday observations within the fixed ${index.meta.selected_history}-week horizon.`:'Outside the fixed training cohort: no learned forecast or intervention. Its observed flow remains in the network score.'} Positive flow means more departures than arrivals; a positive transfer adds bikes. Zero remaining net outflow is balanced; a negative remainder means net inflow remains.</p></div>
  <section className="mobility-panel" aria-labelledby="mobility-budget-heading"><h3 id="mobility-budget-heading">What does a larger move budget change?</h3><p>The model re-solves at each budget with this date, station limit and protection. A better forecast objective need not produce a better observed outcome.</p><p>Select a budget label to use it; the curve and selected-morning outcome update together.</p><div className="mobility-curve" role="group" aria-label="Select a bike budget by its observed residual">{curve.map(r=><div key={r.budget}><button className="study-plot-choice" aria-pressed={budget===r.budget} onClick={()=>setBudget(r.budget)} aria-label={`Use ${r.budget} bike budget: ${fmt(r.residual)} observed residual`}>{r.budget} bikes</button><div><i style={{width:`${r.residual/maxCurve*100}%`}} /></div><strong>{fmt(r.residual)}</strong></div>)}</div><details className="data-details"><summary>Budget comparison values</summary><div className="table-wrap" tabIndex={0} role="region" aria-label="Budget comparison values"><table><thead><tr><th>Bike budget</th><th>Forecast residual</th><th>Observed residual</th><th>Moved</th><th>Stations</th></tr></thead><tbody>{curve.map(r=><tr key={r.budget}><th scope="row">{r.budget}</th><td>{fmt(r.forecast_residual,1)}</td><td>{r.residual}</td><td>{r.moves}</td><td>{r.touched}</td></tr>)}</tbody></table></div></details></section>
  <section className="mobility-period" id="mobility-period"><p className="eyebrow">Every test morning</p><h3>Keep the whole period in view.</h3><p>2–22 March 2026 · {budget} bike budget · {touch} station limit · <strong>no protected station</strong>. Each tile shows exact-allocation residual minus the selected reference. Negative is better; positive is worse. Select a tile to inspect that morning and clear protection.</p><ChoiceControl label="Compare observed residual with" value={periodBaseline} options={[{value:'no_action',label:'No relocation'},{value:'greedy',label:'Greedy pairing'}]} onChange={value=>setPeriodBaseline(value as 'no_action'|'greedy')} disabled={!ready}/><div className="mobility-day-strip">{period.map(d=><button key={d.date} className={d.delta>0?'worse':''} aria-pressed={d.date===date} onClick={()=>inspectMorning(d.date)} aria-label={`${labelDate(d.date)}: ${signed(d.delta)} ${mobilityLabels[periodBaseline]} residual difference, no protection`}><span>{d.date.slice(8)} Mar</span><strong>{signed(d.delta)}</strong></button>)}</div><p>The plan is worse on {period.filter(d=>d.delta>0).length}, tied on {period.filter(d=>d.delta===0).length} and better on {period.filter(d=>d.delta<0).length} of 21 mornings. Mean difference: {signed(period.reduce((s,d)=>s+d.delta,0)/period.length)} flow units.</p><button className="mobility-text-button" onClick={showAdverse}>{worst.delta>0?'Inspect the largest worsening':worst.delta<0?'Inspect the smallest improvement':'Inspect a tied morning'} →</button><p className="mobility-small">This example is selected after evaluation at the current budgets and reference, with earliest-date ties. If all days improve, it shows the smallest improvement.</p></section>
  <details className="data-details mobility-network"><summary>Inspect the complete station network</summary><p>Sorted by absolute observed residual under the exact plan. Showing {showAll?index.stations.length:20} of {index.stations.length}; every station is included in the score above.</p><button className="mobility-text-button" onClick={()=>setShowAll(!showAll)}>{showAll?'Show largest 20 residuals':'Show all stations'}</button><div className="table-wrap" tabIndex={0} role="region" aria-label="Full station network"><table><thead><tr><th>Station</th><th>Departures</th><th>Arrivals</th><th>Forecast flow</th><th>Transfer</th><th>Remaining net outflow</th></tr></thead><tbody>{network.slice(0,showAll?network.length:20).map(s=><tr key={s.id}><th scope="row">{s.name}<small>{s.id}{s.eligible?'':' · outside cohort'}</small></th><td>{day.departures[s.i]}</td><td>{day.arrivals[s.i]}</td><td>{day.forecast_num[s.i]===null?'N/A':signed(day.forecast_num[s.i]!/60)}</td><td>{signed(plan.transfer[s.i])}</td><td>{signed(day.actual[s.i]-plan.transfer[s.i])}</td></tr>)}</tbody></table></div></details>
 </div>
 </StudyWorkbench>
 </fieldset>;
}
