import {useEffect,useMemo,useState} from 'react';
import {evaluateWeek,policies,policyNames,type RetailIndex,type Policy} from '../lib/retail';
const fmt=(v:number,d=0)=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:d}).format(v);
const dateLabel=(v:string)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(v+'T00:00:00Z'));
const shortDate=(v:string)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(v+'T00:00:00Z'));
const signed=(v:number)=>{const n=Math.abs(v)<1e-8?0:v;return `${n>0?'+':''}${fmt(n,1)}`;};
function Tradeoff({index,priority}:{index:RetailIndex;priority:number}){
 const rows=index.meta.budget_factors.map(factor=>({factor,scenario:index.summaries.find(r=>r.factor===factor&&r.priority===priority&&r.policy==='scenario')!.mean_loss,mean:index.summaries.find(r=>r.factor===factor&&r.priority===priority&&r.policy==='mean')!.mean_loss}));
 const max=Math.max(...rows.flatMap(r=>[r.scenario,r.mean]))*1.12||1;
 const x=(i:number)=>80+i*180,y=(v:number)=>250-v/max*210;
 return <div className="retail-panel retail-tradeoff"><h3>What does a larger budget change?</h3><p>Mean weighted mismatch over all 23 test weeks, with the current priority and no protected product. A lower score is better under this preference.</p>
 <svg viewBox="0 0 680 320" role="img" aria-labelledby="retail-curve-title"><title id="retail-curve-title">Scenario allocation and eight-week mean mismatch at four budget factors. Exact values follow in the table.</title>
 {[0,0.5,1].map(t=><g key={t}><line x1="80" x2="620" y1={y(max*t)} y2={y(max*t)} stroke="#ccd2c7"/><text x="68" y={y(max*t)+5} textAnchor="end" className="axis-label">{fmt(max*t)}</text></g>)}
 {(['scenario','mean'] as const).map(key=><g key={key}><polyline points={rows.map((r,i)=>`${x(i)},${y(r[key])}`).join(' ')} fill="none" stroke={key==='scenario'?'#08695e':'#a54a25'} strokeWidth="3" strokeDasharray={key==='mean'?'7 5':undefined}/>{rows.map((r,i)=><circle key={i} cx={x(i)} cy={y(r[key])} r="4" fill={key==='scenario'?'#08695e':'#a54a25'}/>)}</g>)}
 {rows.map((r,i)=><text key={i} x={x(i)} y="278" textAnchor="middle" className="axis-label">{r.factor*100}%</text>)}<text x="350" y="307" textAnchor="middle" className="axis-label">Budget factor · relative to the eight-week mean</text></svg>
 <p className="retail-curve-legend">Solid teal: scenario allocation. Dashed copper: eight-week mean.</p><table className="retail-mobile-curve"><caption>Mean weighted mismatch · all test weeks</caption><thead><tr><th>Budget</th><th>Scenario</th><th>Mean rule</th></tr></thead><tbody>{rows.map(r=><tr key={r.factor}><th scope="row">{r.factor*100}%</th><td>{fmt(r.scenario,1)}</td><td>{fmt(r.mean,1)}</td></tr>)}</tbody></table><details className="data-details"><summary>Exact budget comparison</summary><div className="table-wrap" tabIndex={0} role="region" aria-label="Budget comparison values"><table><thead><tr><th>Budget factor</th><th>Scenario mismatch</th><th>Mean-rule mismatch</th></tr></thead><tbody>{rows.map(r=><tr key={r.factor}><th scope="row">{r.factor*100}%</th><td>{fmt(r.scenario,1)}</td><td>{fmt(r.mean,1)}</td></tr>)}</tbody></table></div></details></div>;
}
export default function RetailExplorer({index}:{index:RetailIndex}){
 const [weekId,setWeekId]=useState(index.meta.default_week),[factor,setFactor]=useState(index.meta.default_factor),[priority,setPriority]=useState(index.meta.default_priority);
 const [protect,setProtect]=useState(''),[minimum,setMinimum]=useState('0'),[showAll,setShowAll]=useState(false),[ready,setReady]=useState(false),[returnToResult,setReturnToResult]=useState(false);
 useEffect(()=>{const restore=()=>{const p=new URLSearchParams(window.location.search);const date=p.get('week');setWeekId(index.weeks.some(w=>w.week===date)?date!:index.meta.default_week);const f=Number(p.get('budget')),l=Number(p.get('priority'));setFactor(index.meta.budget_factors.includes(f)?f:index.meta.default_factor);setPriority(index.meta.priorities.includes(l)?l:index.meta.default_priority);const product=p.get('protect');setProtect(index.products.some(p=>p.code===product)?product!:'');const raw=p.get('minimum')||'0';const n=Number(raw);setMinimum(Number.isSafeInteger(n)&&n>=0?String(n):raw);};restore();setReady(true);window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[]);
 useEffect(()=>{if(!ready)return;const p=new URLSearchParams({week:weekId,budget:String(factor),priority:String(priority)});if(protect){p.set('protect',protect);p.set('minimum',minimum);}window.history.replaceState(null,'',window.location.pathname+'?'+p+window.location.hash);},[weekId,factor,priority,protect,minimum,ready]);
 useEffect(()=>{if(returnToResult){const target=document.getElementById('retail-week-outcome');if(target){target.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});target.focus({preventScroll:true});}setReturnToResult(false);}},[weekId,returnToResult]);
 const codes=index.products.map(p=>p.code),week=index.weeks.find(w=>w.week===weekId)!;
 const unprotected=useMemo(()=>evaluateWeek(week,factor,priority,index.meta.selected_window,codes),[week,factor,priority]);
 const result=useMemo(()=>{try{const minima=codes.map(code=>code===protect?Number(minimum):0);return {value:evaluateWeek(week,factor,priority,index.meta.selected_window,codes,minima),error:''};}catch(error){return {value:null,error:error instanceof Error?error.message:'Unable to calculate this allocation.'};}},[week,factor,priority,protect,minimum]);
 const period=useMemo(()=>index.weeks.map(w=>({week:w.week,...evaluateWeek(w,factor,priority,index.meta.selected_window,codes)})),[factor,priority]);
 const comparison=index.comparisons.find(r=>r.factor===factor&&r.priority===priority&&r.baseline==='mean')!;
 const periodSummary=policies.map(policy=>index.summaries.find(r=>r.factor===factor&&r.priority===priority&&r.policy===policy)!);
 const scenario=result.value?.results.scenario,mean=result.value?.results.mean;
 const productRows=scenario?index.products.map((p,i)=>({...p,i,q:scenario.allocation[i],baseline:mean!.allocation[i],actual:week.actual[i]})).sort((a,b)=>Math.abs(b.q-b.baseline)-Math.abs(a.q-a.baseline)||(a.code<b.code?-1:1)):[];
 const visible=showAll?productRows:productRows.slice(0,10),scale=Math.max(1,...productRows.flatMap(p=>[p.q,p.baseline,p.actual]));
 const custom=Boolean(protect&&Number(minimum)>0),unitsLostElsewhere=scenario?scenario.allocation.reduce((sum,q,i)=>sum+(codes[i]===protect?0:Math.max(unprotected.results.scenario.allocation[i]-q,0)),0):0;
 const extraUsed=scenario?unprotected.results.scenario.unused-scenario.unused:0;
 return <div>
  <fieldset className="retail-controls" disabled={!ready}><legend className="sr-only">Choose an allocation scenario</legend>
   <label>Week beginning<select value={weekId} onChange={e=>setWeekId(e.target.value)}>{index.weeks.map(w=><option key={w.week} value={w.week}>{dateLabel(w.week)}</option>)}</select></label>
   <label>Unit budget factor<select value={factor} onChange={e=>setFactor(Number(e.target.value))} aria-describedby="retail-control-help">{index.meta.budget_factors.map(f=><option key={f} value={f}>{f*100}% of recent mean activity</option>)}</select></label>
   <label>Shortfall priority<select value={priority} onChange={e=>setPriority(Number(e.target.value))} aria-describedby="retail-control-help"><option value={0.5}>50% · equal weights (1:1)</option><option value={0.8}>80% · shortfall 4× (4:1)</option><option value={0.95}>95% · shortfall 19× (19:1)</option></select></label>
  </fieldset>
  <p className="retail-control-help" id="retail-control-help"><strong>{fmt(unprotected.budget)} units available.</strong> Budget is a hypothetical total unit count. Priority weights shortfall against leftovers; it is not a service target. Under a tight budget, changing priority may leave the allocation unchanged: the same products still have the highest marginal benefit. Allocations are calculated in your browser from frozen historical inputs, using the validated {index.meta.selected_window}-week scenario window.</p>
  <details className="retail-protection"><summary>Reserve a minimum for one product</summary><p>This requirement applies to every policy within the same budget. It changes the selected week’s calculation; the whole-period reference below stays unprotected.</p><div className="retail-protection-fields">
   <label>Protected product<select disabled={!ready} value={protect} onChange={e=>setProtect(e.target.value)}><option value="">No protected product</option>{index.products.map(p=><option key={p.code} value={p.code}>{p.code} · {p.name}</option>)}</select></label>
   <label>Minimum units<input disabled={!ready||!protect} type="number" min="0" step="1" value={minimum} onChange={e=>setMinimum(e.target.value)} aria-describedby={result.error?'retail-input-error':'retail-control-help'} aria-invalid={Boolean(result.error)}/></label>
   <button disabled={!ready} onClick={()=>{setProtect('');setMinimum('0');}}>Clear minimum</button>
  </div></details>
  <div id="retail-week-outcome" role="region" aria-label="Selected week allocation" tabIndex={-1}>
  {result.error?<p className="retail-alert" role="alert" id="retail-input-error">{result.error}</p>:<div className="retail-results">
   <div className="retail-result-heading"><h3 id="retail-allocation-heading" tabIndex={-1}>Allocation for {dateLabel(weekId)}</h3><p>{custom?'Custom minimum applied':'No protected minimum'} · {fmt(result.value!.budget)}-unit budget</p></div>
   <div className="retail-kpis" aria-live="polite" aria-atomic="true"><div><span>Recorded-activity shortfall</span><strong>{fmt(scenario!.shortfall)}</strong><small>units below recorded activity</small></div><div><span>Leftover allocation</span><strong>{fmt(scenario!.leftover)}</strong><small>units above recorded activity</small></div><div><span>Weighted mismatch</span><strong>{fmt(scenario!.loss,1)}</strong><small>weighted units · lower is better</small></div></div>
   <p className="retail-decision-note">The scenario allocation uses <strong>{fmt(result.value!.budget-scenario!.unused)} units</strong> and leaves {fmt(scenario!.unused)} of the budget unused. Its mismatch is {fmt(Math.abs(scenario!.loss-mean!.loss),1)} weighted units {scenario!.loss<mean!.loss-1e-8?'lower':scenario!.loss>mean!.loss+1e-8?'higher':'away from'} than the eight-week mean rule{Math.abs(scenario!.loss-mean!.loss)<1e-8?' (a tie)':''}. Recorded-activity coverage is {scenario!.coverage===null?'undefined because no activity was recorded':fmt(scenario!.coverage*100,1)+'%'}, not measured customer service.</p>
   {custom&&<p className="retail-alert">Compared with the unprotected scenario allocation, {fmt(unitsLostElsewhere)} fewer units go to other products and {fmt(extraUsed)} more budget units are used. A minimum below the unprotected allocation may change nothing. Its effect on future observations remains uncertain.</p>}
   <div className="retail-panel"><h3>Same budget. Different allocation rules.</h3><p>All policies use the same {custom?'product minimum, ':''}budget and priority. Perfect information knows the week’s recorded activity in advance and is not available when planning.</p>
    <div className="table-wrap" tabIndex={0} role="region" aria-label="Selected week policy comparison"><table><caption>{dateLabel(weekId)} · {priority*100}% shortfall priority · quantities in units</caption><thead><tr><th>Policy</th><th>Allocated</th><th>Shortfall</th><th>Leftover</th><th>Weighted mismatch</th></tr></thead><tbody>{policies.map(p=>{const r=result.value!.results[p];return <tr key={p} className={p==='scenario'?'selected-row':''}><th scope="row">{policyNames[p]}</th><td>{fmt(result.value!.budget-r.unused)}</td><td>{fmt(r.shortfall)}</td><td>{fmt(r.leftover)}</td><td>{fmt(r.loss,1)}</td></tr>;})}</tbody></table></div>
   </div>
   <div className="retail-panel"><div className="retail-allocation-heading"><h3>Where the units go</h3><label>Products shown<select disabled={!ready} value={showAll?'all':'10'} onChange={e=>setShowAll(e.target.value==='all')}><option value="10">10 largest changes versus mean rule</option><option value="all">All 30 products</option></select></label></div><p>Showing {visible.length} of 30 products, ranked by absolute allocation change versus the mean rule. Totals always include all 30. Recorded activity is revealed after the allocation decision.</p>
    <div className="retail-bar-legend"><span>Scenario allocation</span><span>Mean rule (outline)</span><span>Recorded activity</span></div>
    <ol className="retail-product-bars">{visible.map(p=><li key={p.code}><div className="retail-product-name"><span>{p.name}<small>{p.code} · {fmt(p.q)} allocated / {fmt(p.actual)} recorded</small></span><strong title="Change versus eight-week mean">{signed(p.q-p.baseline)}</strong></div><div className="retail-bar-track" aria-hidden="true"><span style={{width:100*p.q/scale+'%'}}/></div><div className="retail-bar-track baseline" aria-hidden="true"><span style={{width:100*p.baseline/scale+'%'}}/></div><div className="retail-bar-track actual" aria-hidden="true"><span style={{width:100*p.actual/scale+'%'}}/></div></li>)}</ol>
    <details className="data-details"><summary>Exact allocations for all 30 products</summary><div className="table-wrap" tabIndex={0} role="region" aria-label="All product allocations"><table><thead><tr><th>Product</th><th>Scenario</th><th>Mean rule</th><th>Recorded activity</th><th>Change</th></tr></thead><tbody>{productRows.map(p=><tr key={p.code}><th scope="row">{p.code} · {p.name}</th><td>{fmt(p.q)}</td><td>{fmt(p.baseline)}</td><td>{fmt(p.actual)}</td><td>{signed(p.q-p.baseline)}</td></tr>)}</tbody></table></div></details>
   </div>
  </div>}
  </div>
  <section className="retail-period" id="retail-period"><h3>Across all 23 test weeks</h3><p>27 June–4 December 2011 · <strong>no protected minimum</strong>. The budget is recalculated before each week using the current {factor*100}% factor. Priority stays at {priority*100}%; changing it changes the meaning of the weighted score.</p>
   <p>The scenario method has {fmt(Math.abs(comparison.mean_difference),1)} {comparison.mean_difference<0?'fewer':'more'} weighted mismatch units per week than the mean rule on average. It performs better on {comparison.better} weeks, ties on {comparison.tied}, and performs worse on {comparison.worse}. Select any week below; negative differences favour the scenario allocation.</p>
   <div className="retail-week-strip" role="group" aria-label="Select a test week by its mismatch difference">{period.map(w=>{const d=w.results.scenario.loss-w.results.mean.loss;return <button key={w.week} disabled={!ready} className={d>1e-8?'worse':''} aria-pressed={w.week===weekId} aria-label={`${dateLabel(w.week)}: ${fmt(Math.abs(d),1)} weighted units ${d>1e-8?'higher':d< -1e-8?'lower':'equal'} mismatch`} onClick={()=>{setWeekId(w.week);setReturnToResult(true);}}><span>{shortDate(w.week)}</span><strong>{signed(d)}</strong></button>;})}</div>
   <p className="retail-control-help">Selecting a week returns you to its allocation above. Product protection, if set, applies only to that selected calculation.</p>
   <div className="retail-panel"><h3>Whole-period comparison</h3><div className="table-wrap" tabIndex={0} role="region" aria-label="Whole-period policy comparison"><table><caption>All 23 test weeks · no protected minimum · mean quantities per week</caption><thead><tr><th>Policy</th><th>Weighted mismatch</th><th>Shortfall</th><th>Leftover</th><th>Coverage of recorded units</th></tr></thead><tbody>{periodSummary.map(r=><tr key={r.policy} className={r.policy==='scenario'?'selected-row':''}><th scope="row">{policyNames[r.policy as Policy]}</th><td>{fmt(r.mean_loss,1)}</td><td>{fmt(r.mean_shortfall,1)}</td><td>{fmt(r.mean_leftover,1)}</td><td>{r.coverage===null?'No recorded activity':fmt(r.coverage*100,1)+'%'}</td></tr>)}</tbody></table></div></div>
   <Tradeoff index={index} priority={priority}/>
  </section>
 </div>;
}
